import {
  ABSOLABS_SET,
  ARCANE_SHADE_SET,
  CHALLENGER_SET,
  COMMANDER_LOOT_SET,
  DAWN_BOSS_SET,
  EXPEDITION_BOSS_LOOT_SET,
  MUSPELL_LEGENDARY_SET,
  MUSPELL_UNIQUE_SET,
  PENSALIR_LEGENDARY_SET,
  PENSALIR_UNIQUE_SET,
  ROOT_ABYSS_LEGENDARY_SET,
  ROOT_ABYSS_UNIQUE_SET,
} from "./sets";
import { EquipmentSetDefinition } from "./types";

export const EQUIPMENT_SET_DEFINITIONS: EquipmentSetDefinition[] = [
  ARCANE_SHADE_SET,
  ABSOLABS_SET,
  CHALLENGER_SET,
  ROOT_ABYSS_UNIQUE_SET,
  ROOT_ABYSS_LEGENDARY_SET,
  PENSALIR_LEGENDARY_SET,
  PENSALIR_UNIQUE_SET,
  MUSPELL_LEGENDARY_SET,
  MUSPELL_UNIQUE_SET,
  DAWN_BOSS_SET,
  COMMANDER_LOOT_SET,
  EXPEDITION_BOSS_LOOT_SET,
];
