import { EquipmentSetDefinition } from "../types";

export const EXPEDITION_BOSS_LOOT_SET: EquipmentSetDefinition = {
  id: "expedition-boss-loot",
  displayName: "원정대 보스 전리품",
  displayOrder: 12,
  minSetCount: 1,
  maxSetCount: 7,
  itemNames: [
    "혼테일의 목걸이",
    "카오스 혼테일의 목걸이",
    "분노한 자쿰의 벨트",
    "데아 시두스 이어링",
    "블랙빈 마크",
    "카오스 핑크빈 마크",
    "아쿠아틱 레터 눈장식",
    "응축된 힘의 결정석",
    "실버블라썸링",
    "시그너스의 코히누르",
    "다크 프리미엄 심볼",
    "크리스탈 웬투스 뱃지",
    "카오스 데아 시두스 이어링",
    "카오스 골든 클로버 벨트",
    "핑크빛 성배",
  ],
  setEffects: [
    {
      key: "physicalDefense",
      label: "물리 방어력",
      unit: "flat",
      values: {
        1: 300,
        2: 500,
        3: 700,
        4: 1_000,
        5: 1_500,
        6: 1_500,
        7: 1_500,
      },
    },
    {
      key: "accuracy",
      label: "명중률",
      unit: "%",
      values: {
        1: 3,
        2: 6,
        3: 10,
        4: 15,
        5: 18,
        6: 20,
        7: 20,
      },
    },
    {
      key: "magicDefense",
      label: "마법 방어력",
      unit: "flat",
      values: {
        1: 300,
        2: 500,
        3: 700,
        4: 1_000,
        5: 1_500,
        6: 1_500,
        7: 1_500,
      },
    },
    {
      key: "maxHp",
      label: "최대 HP",
      unit: "flat",
      values: {
        1: 1_000,
        2: 2_000,
        3: 4_000,
        4: 6_000,
        5: 8_000,
        6: 10_000,
        7: 12_000,
      },
    },
    {
      key: "hpRecovery",
      label: "HP 회복력",
      unit: "flat",
      values: {
        1: 100,
        2: 200,
        3: 300,
        4: 400,
        5: 500,
        6: 500,
        7: 500,
      },
    },
    {
      key: "expRate",
      label: "경험치 획득량",
      unit: "%",
      values: {
        3: 3,
        4: 7,
        5: 7,
        6: 7,
        7: 7,
      },
    },
    {
      key: "bossDefense",
      label: "보스 방어력 증가",
      unit: "%",
      values: {
        4: 3,
        5: 3,
        6: 3,
        7: 7,
      },
    },
    {
      key: "bossAttack",
      label: "보스 공격력 증가",
      unit: "%",
      values: {
        5: 3,
        6: 7,
        7: 7,
      },
    },
    {
      key: "physicalDamageReduction",
      label: "물리 피해 감소",
      unit: "%",
      values: {
        6: 4,
        7: 8,
      },
    },
    {
      key: "magicDamageReduction",
      label: "마법 피해 감소",
      unit: "%",
      values: {
        6: 4,
        7: 8,
      },
    },
    {
      key: "maxMp",
      label: "최대 MP",
      unit: "flat",
      values: {
        7: 10_000,
      },
    },
    {
      key: "physicalDamage",
      label: "물리 대미지",
      unit: "%",
      values: {
        7: 5,
      },
    },
    {
      key: "magicDamage",
      label: "마법 대미지",
      unit: "%",
      values: {
        7: 5,
      },
    },
  ],
};
